url: http://www.coffeegana.com

title: 咖纳咖啡

keywords: 咖纳咖啡

description: 咖纳咖啡

permalink: /products/:title.html

address: 广东省佛山市顺德区勒流光明中路9号创世纪大厦1楼

tel: 0757-23660117

qq: 3572576627

email: 3572576627@qq.com

weidian: https://weidian.com/?userid=970849833

relative_permalinks: false

exclude:
  - README.md

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/js
    - _assets/css
  compress:
    css: true
    js: true
  cache: asset-cache
  gzip: []
